

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	private int index;
    public void someLibraryMethod() {
        System.out.print("p");
    }
    
    public static void main(String args[]) {		
    	Library l = new Library();
    	l.someLibraryMethod();
	}
}
